### ISSUE TITLE
CARMA Platform shuts down when /opt/carma/vehicle is symlinked to carma-config's example_calibration_folder/vehicle folder

### ISSUE THREAD

**Issue by JonSmet** [usdot-fhwa-stol/carma-config#262]
### Summary

When launching CARMA Platform with the development config, it is expected that a user can symlink their /opt/carma/vehicle folder to carma-config's example_calibration_folder/vehicle folder. This is accomplished as part of the development environment setup instructions on Confluence: https://usdot-carma.atlassian.net/wiki/spaces/CRMPLT/pages/488472599/Setup+CARMA+Platform+Runtime#Setup-the-%2Fopt%2Fcarma-folder

Currently, when the carma-config/example_calibration_folder/vehicle folder is used, CARMA Platform shuts down during launch with the following error:

```
[33mplatform_ros2                 |[0m chmod: cannot access '/opt/carma/vehicle/calibration/cloud_permission/carma-cloud-test-1.pem': No such file or directory
[33mplatform_ros2                 |[0m Task exception was never retrieved
[33mplatform_ros2                 |[0m future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:226> exception=CalledProcessError(1, ['sudo', 'chmod', '400', '/opt/carma/vehicle/calibration/cloud_permission/carma-cloud-test-1.pem'])>
[33mplatform_ros2                 |[0m Traceback (most recent call last):
[33mplatform_ros2                 |[0m   File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
[33mplatform_ros2                 |[0m     await self.__process_event(next_event)
[33mplatform_ros2                 |[0m   File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
[33mplatform_ros2                 |[0m     visit_all_entities_and_collect_futures(entity, self.__context))
[33mplatform_ros2                 |[0m   File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
[33mplatform_ros2                 |[0m     futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
[33mplatform_ros2                 |[0m   File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
[33mplatform_ros2                 |[0m     futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
[33mplatform_ros2                 |[0m   File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
[33mplatform_ros2                 |[0m     futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
[33mplatform_ros2                 |[0m   [Previous line repeated 4 more times]
[33mplatform_ros2                 |[0m   File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
[33mplatform_ros2                 |[0m     sub_entities = entity.visit(context)
[33mplatform_ros2                 |[0m   File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit
[33mplatform_ros2                 |[0m     return self.execute(context)
[33mplatform_ros2                 |[0m   File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/include_launch_description.py", line 130, in execute
[33mplatform_ros2                 |[0m     launch_description = self.__launch_description_source.get_launch_description(context)
[33mplatform_ros2                 |[0m   File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_source.py", line 84, in get_launch_description
[33mplatform_ros2                 |[0m     self._get_launch_description(self.__expanded_location)
[33mplatform_ros2                 |[0m   File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/python_launch_description_source.py", line 51, in _get_launch_description
[33mplatform_ros2                 |[0m     return get_launch_description_from_python_launch_file(location)
[33mplatform_ros2                 |[0m   File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/python_launch_file_utilities.py", line 68, in get_launch_description_from_python_launch_file
[33mplatform_ros2                 |[0m     return getattr(launch_file_module, 'generate_launch_description')()
[33mplatform_ros2                 |[0m   File "/opt/carma/install_ros2/carma/share/carma/launch/message.launch.py", line 213, in generate_launch_description
[33mplatform_ros2                 |[0m     subprocess.check_call(['sudo','chmod','400', keyfile])
[33mplatform_ros2                 |[0m   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
[33mplatform_ros2                 |[0m     raise CalledProcessError(retcode, cmd)
[33mplatform_ros2                 |[0m subprocess.CalledProcessError: Command '['sudo', 'chmod', '400', '/opt/carma/vehicle/calibration/cloud_permission/carma-cloud-test-1.pem']' returned non-zero exit status 1.
```

### Version

4.3.0 (Current)

### Expected Behavior

A carma-cloud-test-1.pem file should be found within the /opt/carma/vehicle/calibration/cloud_permission directory. As mentioned above, a user should be able to symlink /opt/carma/vehicle to the carma-config's example_calibration_folder/vehicle folder.

### Actual Behavior

The carma-cloud-test-1.pem file is not found at launch time, and CARMA Platform shuts down.

### Steps to Reproduce the Actual Behavior

1. Launch CARMA with the development config and with /opt/carma/vehicle symlinked to carma-config's example_calibration_folder/vehicle folder.
2. Verify that CARMA Platform shuts down with the error displayed previously in this issue.

**Comment by JonSmet** [comment]
Closed by PR #261
